### ISSUE TITLE
Windows编译字体缺失问题

### ISSUE THREAD

**Issue by quansilong** [liweitianux/resume#1]
Xelatex编译提示! Package fontspec Error: The font "Source Han Serif SC" cannot be found.
请问在Windows下如何使用IBM Plex (Serif, Mono)和Source Han Serif字体？新手不太懂，忘指教。

**Comment by liweitianux** [comment]
模板所需的字体（`FontAwesome`, `Source Han Serif`, `IBM Plex`）链接已在首页给出，请到相应页面下载字体（OTF 或 TTF 格式均可），然后将文件复制到 Windows 的字体目录（`C:\Windows\Fonts`）。应该就可以了。

如有疑问，可搜索网上相关资料。

**Comment by liweitianux** [comment]
@quansilong , 我想你应该解决这个问题了。我将关闭这个 Issue。如果还有问题，请重新打开此 Issue 或提交新的 Issue，谢谢。

**Comment by sulf1ron** [comment]
Windows 下安装字体时需要选择为所有用户安装

**Comment by MiMO33** [comment]
> Windows 下安装字体时需要选择为所有用户安装

thanks

**Comment by jusway** [comment]
> Windows 下安装字体时需要选择为所有用户安装

谢谢大佬
