### ISSUE TITLE
macOS 上编译报错: Undefined control sequence. \locationSymbol ->\faMapMarkerAlt

### ISSUE THREAD

**Issue by zhang-junjian** [liweitianux/resume#10]
![image](https://user-images.githubusercontent.com/29877823/134867327-db7c7527-85ae-4323-afcd-54d020a33455.png)

**Comment by liweitianux** [comment]
请问你具体是如何编译的？Linux 平台下直接使用我的 Makefile 吗？

根据截图的错误看，感觉是没有找到相应的 sty 包，也可能是 sty 包里的内容不对。

请附上完整的编译日志。

**Comment by zhang-junjian** [comment]
macos，安装字体成功后可以运行成功。macOS与ubuntu安装字体方式不一样

**Comment by liweitianux** [comment]
:+1: 

可以的话，请在此简要描述一下 macOS 的字体安装方法，谢谢。

如果没有其他问题的话，请关闭此问题。

**Comment by liweitianux** [comment]
呃，没有回应。。。关闭该问题。
