### ISSUE TITLE
Undefined control sequence. \makeheader错误

### ISSUE THREAD

**Issue by isping** [liweitianux/resume#11]
使用XeLatex编译出现Undefined control sequence. \makeheader 错误

软件环境：
MikTex+TexStudio@Win1
![阿里旺旺图片20211120121012](https://user-images.githubusercontent.com/4645233/142714015-bced2227-5b77-4436-b5ce-f994046cc814.jpg)

**Comment by isping** [comment]
字体问题，已解决。

**Comment by liweitianux** [comment]
@isping 厉害。LaTeX 的错误信息有时很费解、莫名其妙。编译出错的几个主要原因是：（1）未安装需要的宏包；（2）环境变量不对导致找不到本仓库自带的宏包；（3）未安装字体或者字体不对。

**Comment by hzhao1997** [comment]
![Uploading image.png…]()
我安装了所有需要的字体，但还是编译失败，您能给点建议吗

**Comment by hzhao1997** [comment]
![GS4~H(ES2(O6Q7GPAPO)`{G](https://user-images.githubusercontent.com/32841739/153797498-01bde374-70db-4bbd-8f43-deae2430d6e9.png)

**Comment by liweitianux** [comment]
@hzhao1997 如果确认字体都安装了（或者修改 `resume.cls` 使用已安装的字体），我搜索到一个可能是 [`microtype` 宏包冲突](https://github.com/CTeX-org/ctex-kit/issues/527) 导致。试试在 `resume.cls` 中禁用 `microtype` 宏包？或者试试升级 `ctex`/`xeCJK` 宏包版本。

**Comment by hzhao1997** [comment]
> @hzhao1997 如果确认字体都安装了（或者修改 `resume.cls` 使用已安装的字体），我搜索到一个可能是 [`microtype` 宏包冲突](https://github.com/CTeX-org/ctex-kit/issues/527) 导致。试试在 `resume.cls` 中禁用 `microtype` 宏包？或者试试升级 `ctex`/`xeCJK` 宏包版本。

试了还是不行... 不过还是谢谢你。

**Comment by liweitianux** [comment]
呃。。。那我也不知道了。我没有 Windows 环境的 TeX 可以测试。考虑肯定有同学在 Windows 平台顺利使用了这个模板，所以这个模板应该问题不大，试试升级或者使用 [MiKTeX](https://miktex.org/) 版本。

另外你可以改用 Windows 肯定有的字体，比如 SimSum/SimHei 等。

**Comment by hzhao1997** [comment]
> 呃。。。那我也不知道了。我没有 Windows 环境的 TeX 可以测试。考虑肯定有同学在 Windows 平台顺利使用了这个模板，所以这个模板应该问题不大，试试升级或者使用 [MiKTeX](https://miktex.org/) 版本。
> 
> 另外你可以改用 Windows 肯定有的字体，比如 SimSum/SimHei 等。

好的，我再研究尝试一下，谢谢。:blush:
