### ISSUE TITLE
请问win系统texstudio显示\makeheader错误该如何解决，错误内容为“Undefined control sequence. \makeheader”，谢谢

### ISSUE THREAD

**Issue by wuenzhe** [liweitianux/resume#12]

**Comment by wuenzhe** [comment]
不太会修改.cls文件以及定义新命令

**Comment by liweitianux** [comment]
根据之前其他同学的问题报告来看，这个错误应该是缺少字体导致的，比如看看 #11 。LaTeX 的报错信息有时很迷...

我也经验有限，而且没在 Windows 环境跑 LaTeX，所以你再尝试一下（或者安装所需的全部字体，或者修改 class 文件里使用的字体）。

**Comment by wuenzhe** [comment]
您好，问题已解决，应该能是.cls文件中定义\locationSymbol时出现的问题。原命令为\faMapMarkerAlt，编译后\makeheader报错，打开pdf无法显示“定位”的图标，改成\faMapMarker后，不会出现报错，且图标正常显示，成功编译。但具体是什么原理我不是很清楚。

**Comment by liweitianux** [comment]
> 原命令为\faMapMarkerAlt，编译后\makeheader报错，打开pdf无法显示“定位”的图标，改成\faMapMarker后，不会出现报错，且图标正常显示，成功编译。

一个可能原因是你安装的 FontAwesome 字体版本太旧，其中不包含 `MapMarkerAlt` 字符。可以检查一下安装的版本是否与 README 所述的 v5.13.1 差不多。
