### ISSUE TITLE
ubuntu 上编译失败：非法字体

### ISSUE THREAD

**Issue by thw1021** [liweitianux/resume#13]
您好，非常感谢您能分享这份精美的简历模板。我在 `Windows 10` 可以编译成功，但在 `Ubuntu 20.04` 上编译时遇到了问题。

`Windows 10` 上的操作 -- 成功：
- 安装 `TexLive 2021`
- 安装需要的字体
- 运行 `latexmk -xelatex resume-zh` 完成编译

`Ubuntu 20.04`  上的操作 -- 失败：
- 安装 `TexLive 2021`
- 安装需要的字体
- 运行 `make all`，编译报错，错误为 `xdvipdfmx:fatal: Invalid font: -1 (3)`，详见 [make.log](https://github.com/liweitianux/resume/files/10276550/make.log)

可以确认模板所要求的字体已安装。
![Screenshot from 2022-12-21 17-46-46](https://user-images.githubusercontent.com/17957650/208874838-40d1ac5b-54da-4114-b77c-d89b42d11e4d.png)

感谢您的帮助。

**Comment by thw1021** [comment]
很奇怪，把这一行注释掉就可以了
https://github.com/liweitianux/resume/blob/30e6d4c3f8f8923accf4f450814617cbbe7ab374/resume.cls#L93

暂时先关闭了。

**Comment by liweitianux** [comment]
你好。这个问题确实奇怪，从日志也看不出什么异常。我后面再搜搜看。

**Comment by liweitianux** [comment]
感觉是 Type1 和 OpenType 的字体冲突导致了。看起来可能 IBM Plex Mono 字体安装了 Type1 类型（比如通过 apt 包）和 OpenType 类型（手动安装）。可以继续调查一下。

看看这个问题: https://tex.stackexchange.com/questions/612718/using-other-fonts-caused-xdvipdfmxfatal-invalid-font-1

**Comment by thw1021** [comment]
> 感觉是 Type1 和 OpenType 的字体冲突导致了

好像确实是

https://tex.stackexchange.com/questions/617157/xelatex-produces-dvipdfmxfatal-invalid-font-1-22-error-only-on-certain-f
