### ISSUE TITLE
Overleaf Template

### ISSUE THREAD

**Issue by oneliey** [liweitianux/resume#14]
请问是否有Overleaf 模版呢？ 如 [YACC: Another Awesome CV](https://github.com/darwiin/yaac-another-awesome-cv)和[Plasmati Graduate CV](https://www.latextemplates.com/template/plasmati-graduate-cv) 一样

**Comment by liweitianux** [comment]
呃，目前还没有...

这个主意不错，我去注册一下 Overleaf 然后看看怎么弄上去 :smiley:

**Comment by liweitianux** [comment]
已经搞定放到 [Overleaf](https://www.overleaf.com/latex/templates/simple-resume-template-for-new-graduate-ying-jie-sheng-jian-li-mo-ban/hxrntvmmvnqt) 上了，欢迎使用并反馈。
