### ISSUE TITLE
How to replace icons?

### ISSUE THREAD

**Issue by Lccc77** [liweitianux/resume#16]
I would like to ask how to change the icon, such as changing the icon for 'birthday cake' to another option?

**Comment by liweitianux** [comment]
Hi. It's quite easy to adjust it to your needs, e.g., the birthday symbol is defined at
https://github.com/liweitianux/resume/blob/master/resume.cls#L105

Cheers.

**Comment by liweitianux** [comment]
Hi @Lccc77 , I guess this question is resolved now. Please reopen if there is any other related questions. Thanks.
