### ISSUE TITLE
图片photo

### ISSUE THREAD

**Issue by zeroshu** [liweitianux/resume#17]
请问怎么加上自己的photo

**Comment by liweitianux** [comment]
你好。

这份简历模板支持照片，需要手动启用：

https://github.com/liweitianux/resume/blob/master/resume-en.tex#L52

1. 将简历照片保存在 tex 文件的相同目录，比如取名为 `photo.jpg`
2. 启用上述那行 `\photo` 指令，指定照片高度及文件名，比如 `\photo{7.5em}{photo}`
3. 编译即可

**Comment by zeroshu** [comment]
好的，我已经明白如何操作了，谢谢您。

**Comment by yuhan1010** [comment]
> 好的，我已经明白如何操作了，谢谢您。

hihi，请问你编译成功了嘛
