### ISSUE TITLE
头像缩放问题

### ISSUE THREAD

**Issue by lishuiwkp** [liweitianux/resume#18]
你好，首先非常感谢你提供这么优秀的简历模版，但是我想请教一下，我在添加完我自己的头像的时候发现我的头像显示不完全（头发部位无法显示完全），原始照片是没问题的。想请教一下你，这个应该调整什么参数来对图片进行适当缩放。谢谢~

**Comment by liweitianux** [comment]
你好。该模板会自动使用一个居中的圆形来裁剪照片，然后得到一个圆形的头像。我感觉应该是这个裁剪产生你所描述的问题吧？

如果你喜欢圆形的头像，那么你需要调整一下输入照片（比如增大四周区域），保证经过该模板的圆形裁剪后效果不错。

如果不喜欢圆形，那么需要手动修改一下模板 [`resume.cls` 的第 317 行](https://github.com/liweitianux/resume/blob/master/resume.cls#L317)，将目前的 `circle[radius=0.5\linewidth];` 替换为 `rectangle (\linewidth, \linewidth);`。

我后面有空再优化一下，能够直接在 `\photo` 命令切换头像形状。

**Comment by lishuiwkp** [comment]
恩恩好，谢谢，我通过调整原始图片可以得到裁剪合适的头像。
