### ISSUE TITLE
楷体字体加粗问题

### ISSUE THREAD

**Issue by qleenju** [liweitianux/resume#19]
您好！感谢提供的非常优秀、美观的简历模板！想请教一个额外的问题...就是模板中提供的字体是Noto Serif CJK SC，但我个人可能更喜欢楷体字体（KaiTi），可是使用后存在一个问题，也即换成KaiTi后，使用\textbf{}命令加粗仅对英文有效，而中文楷体无法加粗。

我大概知道原因，因为一般默认安装的楷体只有标准字重的字体，没有加粗版本的字体（像华文粗楷等字体也并不是免费商用的）。然后的话我也尝试了网上提及的伪粗体（Fake Bold）算法，不过似乎也发挥作用...

想请教下您知道相应的解决方法吗？抑或KaiTi字体暂时确实无法加粗呢？

祝好~

**Comment by qleenju** [comment]
不好意思，打错字了，第二段更正为"也没发挥作用..."

**Comment by liweitianux** [comment]
你好。

根据我的有限理解，中文排版其实没有粗体这个概念，但是使用宋体、黑体、楷体和仿宋这四种主要字体来实现强调等需求。

所以我建议使用 **黑体** 来代替 **楷体加粗**，比如使用如下方式：

```tex
\setCJKmainfont{KaiTi}[BoldFont=SimHei]
```

另外，也可以使用下划线替代粗体来用于强调。

希望能解决你的问题。

**Comment by qleenju** [comment]
好的我知道了，感谢感谢！
