### ISSUE TITLE
文档大小并非A4

### ISSUE THREAD

**Issue by MuttonYung** [liweitianux/resume#20]
A4应当是210mm X 297mm

<img width="272" alt="屏幕截图 2024-03-19 140932" src="https://github.com/liweitianux/resume/assets/55025557/e867239a-b0ea-440a-bbc2-888b2a139c07">

**Comment by liweitianux** [comment]
你好，我检查了一下，没有发现问题。

A4 纸张大小是在 `resume.cls` 里面指定的：

https://github.com/liweitianux/resume/blob/633dddf40bd3cd733f1c1ba93769aac562dc0985/resume.cls#L30-L34

然后在简历文件 `resume-*.tex` 里面直接使用 `\documentclass{resume}`，不再指定纸张大小。

我编译的 PDF 显示纸张大小确实为 A4：

```
% pdfinfo resume-en.pdf   
Title:           Resume | Weitian LI 
Keywords:        BSD, Linux, Programming, Python, C, Shell, DevOps, SysAdmin
Author:          Weitian LI
Creator:         LaTeX with hyperref
Producer:        xdvipdfmx (20220710)
CreationDate:    Wed Mar 13 15:50:57 2024 CST
Custom Metadata: no
Metadata Stream: no
Tagged:          no
UserProperties:  no
Suspects:        no
Form:            none
JavaScript:      no
Pages:           2
Encrypted:       no
Page size:       595.28 x 841.89 pts (A4)  <<<===
Page rot:        0
File size:       30123 bytes
Optimized:       no
PDF version:     1.5
```

可能你在哪里设置了额外的纸张大小？

**Comment by MuttonYung** [comment]
非常抱歉，可能是浏览器的问题，Edge显示的结果像我说的一样比A4大了一圈，Chrome浏览器打开后显示是正常的大小。
