### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by claviering** [liweitianux/resume#3]
直接使用 make 命令是不行，`Failed to load ToUnicode CMap for font "FontAwesome5Free-Solid"` resume-en.tex resume-zh.tex 都缺少引用包 `\usepackage{./fontawesome5/fontawesome5}`

**Comment by liweitianux** [comment]
1. 我刚刚测试了 `make clean; make`，一切正常。这是完整的日志 http://dpaste.com/2JDQJ71
2. `fontawesome5` 包直接在模板文件 `resume.cls` 中加载.

从你给的错误看，感觉像是 Font Awesome 字体未安装好，导致 XeLaTeX 找不到。

**Comment by claviering** [comment]
好，我再试试
