### ISSUE TITLE
How to make the awesome icon bigger

### ISSUE THREAD

**Issue by chenxofhit** [liweitianux/resume#4]
Thanks for your good job! 
My question is how to make the icons look bigger?

**Comment by liweitianux** [comment]
Hello. Thank you for your interest in my resume template.

I'm sorry for the late reply. I think it's easy to enlarge the icons (at least it shouldn't be hard). I'll find some time to figure it out this weekend and reply to you then.

Cheers,

**Comment by chenxofhit** [comment]
Thank you very much !

**Comment by liweitianux** [comment]
Hi. I've just updated this resume class to support to adjust the icon size. You can find the changes in commits [class: Add '\iconsize' to adjust the icon size](https://github.com/liweitianux/resume/commit/f9a2d84b301d250908af8aa3681b11d698cd5868) and [resume: Increase icon size to '\Large'](https://github.com/liweitianux/resume/commit/6b54bf48ecc50105ebff043663798902e9fc866c). I've also updated the resume PDF so you can have a quick look.

Cheers,

**Comment by chenxofhit** [comment]
Actually, the previous version is okay. I find It is with the issue of my PDF reader. Anyhow, your work contributes as an optional choice for the users. This issue should be solved now. Thanks very much for your work and if you do not have any supplement the issue should be closed.

**Comment by liweitianux** [comment]
Cool. Thank you for the nice feedback. I'll close this issue then.
