### ISSUE TITLE
求职意向选项

### ISSUE THREAD

**Issue by PengNi** [liweitianux/resume#5]
Hi @liweitianux ,

感谢分享这么好的模板！

现在我想把“求职意向”加在简历上，但没找到相应标签。
我尝试过用自定义`\icontext`加在profile里，但感觉并不太美观。
请问有更好的处理方法吗？比如说我想加在`\name`同一行，一个在最左，一个在最右。

Best,
Peng

**Comment by liweitianux** [comment]
Hi Peng,

你可以在 `resume-{zh,en}.tex` 启用 `\tagline`，在其中写上意向岗位（以及其他信息，比如工作地点）。该信息会显示在姓名和基本信息之间。我提供了两个常见用法，供参考。

Cheers,

**Comment by PengNi** [comment]
谢谢！抱歉之前没注意到注释信息。
