### ISSUE TITLE
PDF及make-fontawesome5.py编译错误

### ISSUE THREAD

**Issue by 5dash** [liweitianux/resume#6]
- `make-fontawesome5.py`文件中第30行应修改为`ICONS_URL = FA_URL + "/tree/master/metadata/icons.yml"`？
- 编译PDF，使用Xelatex命令，`address`图标未加载，提示`Undefined control sequence.
\locationSymbol ->\faMapMarkerAlt `
![image](https://user-images.githubusercontent.com/53204626/65161701-9bfdc980-da6a-11e9-987d-64bf2ef1222a.png)

![Snipaste_2019-09-18_23-06-08](https://user-images.githubusercontent.com/53204626/65161573-5fca6900-da6a-11e9-9155-d6fa3c97fcb5.png)

**Comment by 5dash** [comment]
according `compilerlog` and `fontawesome5.sty`file, remove "Alt" from these code `\faMapMarkerAlt`, `\faFileAlt`, `\faCalendarAlt` the bulid is complete

**Comment by liweitianux** [comment]
谢谢。我会在周末修复这个问题。

**Comment by liweitianux** [comment]
Hi @woxj，我测试了一遍，发现这份简历模板没有问题。请更新至最新的 `master` 分支，同时安装最新的 FontAwesome 字体重试。

1. `make-fontawesome5.py` 里的 `ICONS_URL` 正确。
2. `faMapMarkerAlt` 图标正常。（直接使用本模板已带的 `fontawesome5.sty` 和 FontAwesome v5.10.1）

**Comment by 5dash** [comment]
@liweitianux 没问题了，之前编译时报404的错，还以为修改那里可以解决。。(这个带`Alt`的图标有点大)

**Comment by Michael7099** [comment]
@liweitianux 您好，将\faMapMarkerAlt, \faFileAlt, \faCalendarAlt中的Alt移除后，其他图标都显示正常，只有{\faAtom}和{\faAward}会报下面的错误，能问一下是什么原因导致的吗？

! Undefined control sequence.
<argument> \faAward 
                    
l.248 \sectionTitle{获奖及证书}{\faAward}

**Comment by 5dash** [comment]
排查步骤如下
1. git clone <repository>
2. 安装readme所述字体
3. 使用texlive2020 xelatex编译resume-en.tex
查看编译是否有问题

Michael7099 <notifications@github.com> 于 2020年5月31日周日 上午11:27写道：

**Comment by liweitianux** [comment]
On May 31, 2020, at 11:27, Michael7099 <notifications@github.com> wrote

您好，将\faMapMarkerAlt, \faFileAlt, \faCalendarAlt中的Alt移除后，其他图标都显示正常，只有{\faAtom}和{\faAward}会报下面的错误，能问一下是什么原因导致的吗？

! Undefined control sequence.
\faAward

l.248 \sectionTitle{获奖及证书}{\faAward}

你好，最近太忙差点忘记回复了，抱歉。

我看了一下 fontawesome5.sty，里面确实定义了 \faAward，所以不应该出现上述问题。

请仔细看一下 xelatex 的输出日志，看看是否加载了正确的 fontawesome5.sty，我推测可能加载了另外一个不一样的版本。

如果还没有解决问题，请将全部日志一起给出来。

祝好

**Comment by Jasonwi** [comment]
@liweitianux 我猜测也是版本的问题，本机测试\faAtom \faAward均可正常显示 @Michael7099

**Comment by Michael7099** [comment]
> @liweitianux 我猜测也是版本的问题，本机测试\faAtom \faAward均可正常显示 @Michael7099

多谢回复，我用的textlive2018，应该是版本问题，把\faAtom \faAward换了别的符号，可以正常显示了。
