### ISSUE TITLE
icon  problem

### ISSUE THREAD

**Issue by wang-zm18** [liweitianux/resume#7]
![image](https://user-images.githubusercontent.com/47704679/85136912-f4206100-b272-11ea-88d8-75e2549ac14e.png)
 hello ,the problem occrus when I use the command "python make-fontawesome5.py". Besides, I see the URL in code has been changed into "https://github.com/FortAwesome/Font-Awesome/tree/master/metadata/icons.yml".  Thank your for your attention!

**Comment by liweitianux** [comment]
Well, the URL to `icons.yml` is actually right...  Nevertheless, I added a comment to the Python script and explained a bit in [this new commit](https://github.com/liweitianux/resume/commit/4f7f041ee1334c77377f4847a4d285e49156a72b).

I have also fixed the YAML loading warning and updated to the latest FontAwesome snapshot.

**Comment by wang-zm18** [comment]
Thank you fro your reply! You are right, I have sucessfully gotten the generated style file "fontawesome5.sty". But I have met another problem: when I use Xelatex to compile the "make-fontawesome5.py” file, it occurs the following problem, I cannot solve this problem. I sincerely hope you help to cope with this probelm. Thank you!
![image](https://user-images.githubusercontent.com/47704679/85204101-9a886700-b344-11ea-950e-68187db2ab40.png)

**Comment by wang-zm18** [comment]
Thank you for your reply. You're right. I have sucessfully gotten the generated file "fontawesome5.sty" file. But I have met another problem: when I use Xelatex to compile the "resume-zh.tex" file , the following probelm occurs. I cannot solve this problem, so I sincerely hope you can help me ! Thank you !

![image](https://user-images.githubusercontent.com/47704679/85204184-40d46c80-b345-11ea-8ffd-1a88d9424ec1.png)

**Comment by liweitianux** [comment]
Ok. I believe you don't have included the `resume.cls` and `fontawesome5.sty` directories in latex's search path. I don't know your environment so I cannot really help here.
I use Linux and put the necessary settings in the `Makefile`. You can have a look and figure out how to do it on Windows.  By the way, I've updated the README and hope you find it helpful.

**Comment by wang-zm18** [comment]
Thank you! I know the problem: I just need to put the generated "fontawesome5.sty" file into the same  path with "resume-zh.tex" source file! Thank you all the same!
