### ISSUE TITLE
成功运行模板

### ISSUE THREAD

**Issue by pubinpubin** [liweitianux/resume#8]
非常感谢作者的解答，人非常好。我谈一下我在Ubuntu上面运行简历模板遇到的问题。首先安装了texlive-full等latex环境，编辑器安装为texmaker。下载下来压缩包，一共运行遇到两次报错。

首次运行报错，原因是找不到fontawesome5.sty。
![353187977](https://user-images.githubusercontent.com/686169/103148357-c2e09a80-4799-11eb-97ab-258f210d3dff.jpg)

根据作者的解答是编辑器找不到样式的路径，将 fontawesome5.sty文件复制出来，与 resume.cls 放在同级目录即可。

 第二次报错是因为找不到FontAwesome 和IBM等字体，
![BF5086FA@C7EE9F0E 891EDF5F](https://user-images.githubusercontent.com/686169/103148413-4ef2c200-479a-11eb-9c95-3198233c8fa8.jpg)

按照作者read me 等文件的指导下载了安装了字体，安装成功顺利跑起来了，简历模板非常精美，谢谢作者的回答。

**Comment by liweitianux** [comment]
不客气。

另外，你可以将错误截图也一并贴出来，这样更直观具体。

**Comment by liweitianux** [comment]
我已经将错误截图增加到问题描述了，现在应该更加清楚具体了。
