### ISSUE TITLE
如何添加正文标题

### ISSUE THREAD

**Issue by cnforChina** [liweitianux/resume#9]
你好，请问如何在首页添加一个居中标题呢？
尝试在\documentclass[zh]{resume} 后 加入{\centering  \textbf{个人简历}} 似乎没什么效果。

**Comment by cnforChina** [comment]
不好意思，弄错了(⊙﹏⊙) 换成\centerline 就好了
出来的结果标题有点偏左，暂时是多打几个空格来解决，有没有更好的办法呢？

**Comment by cnforChina** [comment]
暂时用\hspace{} 搞定。为什么\centerline的结果会偏左一些？

**Comment by liweitianux** [comment]
你好，我刚刚尝试了一下这样修改：

```tex
\begin{document}

\begin{minipage}{\linewidth}
  \centerline{\emph{个人简历}}
\end{minipage}

\makeheader
```

居中效果没有问题（用尺子测量过）：

![Screenshot_2021-03-21_21-33-31](https://user-images.githubusercontent.com/686169/111906776-48b86d00-8a8d-11eb-929f-f6ddf41f76cb.png)

（不加那个 `begin{minipage}`，居中效果也是一样没问题的）

**Comment by cnforChina** [comment]
找到问题了。 是我\centerline{}加的地方不对，放在\begin{document} 之前了 (＞﹏＜)...

谢谢

**Comment by Alafun** [comment]
@liweitianux 请问性别和个人照片怎么设置呀

**Comment by Alafun** [comment]
> @liweitianux 请问性别和个人照片怎么设置呀

% \photo{<height>}{<filename>} 这是照片的设置方法，在注释里面，我blind了。现在就是性别了

**Comment by Alafun** [comment]
> ```
> \begin{document}
> 
> \begin{minipage}{\linewidth}
>   \centerline{\emph{个人简历}}
> \end{minipage}
> 
> \makeheader
> ```

```diff
\begin{document}
\makeheader
+\begin{minipage}{\linewidth}
+  \centerline{\emph{个人简历}}
+\end{minipage}
```

**Comment by liweitianux** [comment]
> > @liweitianux 请问性别和个人照片怎么设置呀
> 
> 现在就是性别了

可以在 [`\profile{}`](https://github.com/liweitianux/resume/blob/master/resume-zh.tex#L31-L41) 里增加 ` \icontext{<icon>}{<性别>}` 来实现。

图标可以去 FontAwesome 找找。
`profile{}` 里的顺序及换行可以根据需要调整。

**Comment by Alafun** [comment]
> 

好的，谢谢大佬。多亏大佬，我才能完成一份精美的简介
